// Autogenerated modular theme exports
import { authTheme } from './modules/auth';
import { dashboardTheme } from './modules/dashboard';
import { programsTheme } from './modules/programs';
import { partnersTheme } from './modules/partners';
import { applyTheme } from './modules/apply';
import { commonTheme } from './modules/common';
import { homeTheme } from './modules/home';

export const componentsTheme = {
  ...authTheme,
  ...dashboardTheme,
  ...programsTheme,
  ...partnersTheme,
  ...applyTheme,
  ...commonTheme,
  ...homeTheme,
};
