export const authTheme = {
  login: {
    input:
      'mt-2 w-full rounded-md border border-slate-200 bg-white px-4 py-3 text-sm text-slate-800 outline-none placeholder:text-slate-400 focus:border-primary/60 focus:ring-2 focus:ring-primary/30',
    checkbox: 'h-4 w-4 rounded border-white/30 bg-white/20 text-primary focus:ring-primary/40',
    primaryButton:
      'inline-flex w-full cursor-pointer items-center justify-center rounded-xl bg-[var(--brand-primary)] px-5 py-3.5 text-[15px] font-bold text-white transition-all hover:bg-[var(--brand-primary)]/90 active:scale-[0.98]',
    forgotPasswordLink: 'font-semibold cursor-pointer text-[var(--brand-primary)] hover:text-[var(--brand-primary)]/80 transition-colors',
    switchModeLink: 'font-semibold cursor-pointer text-[var(--brand-primary)] hover:text-[var(--brand-primary)]/80 transition-colors',
    slideIndicatorWrapper:
      'inline-flex gap-2 rounded-full border border-white/40 bg-white/15 px-3 py-1 shadow-sm shadow-black/20 backdrop-blur',
    slideDotActive: 'h-2 w-2 rounded-full bg-primary/100 shadow-sm shadow-primary/100/40',
    slideDotInactive: 'h-2 w-2 rounded-full bg-white/70',
    heroEyebrow: 'text-xs font-semibold uppercase tracking-[0.24em] text-primary/20',
    heroTitle: 'text-3xl font-extrabold leading-tight',
    heroDescription: 'text-sm text-primary/10',
    pageBackground: 'bg-slate-50',
    imagePanelBackground: 'bg-slate-50',
    heroOverlay: 'absolute inset-0 bg-gradient-to-t from-primary/85 via-primary/40 to-transparent',
    heroTextContainer: 'absolute inset-x-0 bottom-0 px-8 pb-12 pt-6 text-white',
    heroLogo: 'h-10 w-auto',
    heroLogoWrapper: 'space-y-4',
    formPanelOuter: 'flex items-center justify-start px-6 py-10 lg:px-20 lg:py-0',
    formPanelInner: 'w-full max-w-xl',
    formHeading: 'text-2xl font-extrabold tracking-tight text-primary sm:text-3xl',
    formSubheading: 'mt-2 text-sm text-slate-600',
    card: 'space-y-4 rounded-2xl border border-slate-100 bg-white/80 p-6 shadow-sm',
    fieldLabel: 'block text-xs font-semibold uppercase tracking-wide text-slate-700',
    helperText: 'text-xs text-slate-600',
    checkboxRow: 'flex items-center justify-between text-xs text-slate-600',
    dividerRow:
      'flex items-center justify-center gap-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-400',
    dividerLine: 'h-px w-8 bg-slate-200',
    socialSection: 'space-y-3 rounded-2xl border border-slate-100 bg-white/80 p-6 shadow-sm',
    socialGrid: 'grid grid-cols-1 gap-3 sm:grid-cols-2',
    googleButton:
      'inline-flex w-full cursor-pointer items-center justify-center gap-3 rounded-xl border border-slate-200 bg-white px-5 py-3.5 hover:shadow-sm active:scale-[0.98] text-[15px] font-bold text-slate-700 transition-all hover:bg-slate-50',
    googleButtonIcon: 'h-5 w-5',
    facebookButton:
      'inline-flex w-full cursor-pointer items-center justify-center gap-3 rounded-xl border border-slate-200 bg-white px-5 py-3.5 hover:shadow-sm active:scale-[0.98] text-[15px] font-bold text-slate-700 transition-all hover:bg-slate-50',
    facebookButtonIcon: 'h-5 w-5',
    secondaryButton:
      'inline-flex w-full cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white px-5 py-3.5 hover:shadow-sm active:scale-[0.98] text-[15px] font-bold text-[var(--brand-primary)] transition-all hover:bg-slate-50 hover:text-[var(--brand-primary)]/80',
    termsLabel: 'mt-1 inline-flex items-center gap-2 text-xs text-slate-600',
    termsLink: 'underline cursor-pointer',
  },
  onboarding: {
    layoutGrid: 'grid min-h-screen grid-cols-1 lg:grid-cols-[minmax(0,1fr)_auto]',
    leftCol: 'relative bg-white lg:overflow-hidden lg:rounded-r-3xl',
    leftCenter: 'flex min-h-screen items-center justify-center px-6 py-10 lg:px-20 lg:py-0',
    logoWrapper: 'mb-8',
    logoImage: 'h-16 w-auto sm:h-20',
    progressGrid: 'flex items-center gap-3',
    progressButtonBase: 'group flex-1',
    progressButtonLocked: 'cursor-not-allowed opacity-60',
    progressBarBase: 'h-1 w-full rounded-full',
    progressBarActive: 'bg-primary',
    progressBarInactive: 'bg-slate-200',
    stepLine: 'mt-6 text-sm text-slate-700',
    stepLineEmphasis: 'font-semibold text-primary',
    questionTitle: 'mt-6 text-4xl font-extrabold tracking-tight text-slate-900',
    questionDescription: 'mt-4 text-base text-slate-600',
    form: 'mt-6 space-y-4',
    fieldError: 'mt-1 text-xs text-primary',
    locationGrid: 'grid grid-cols-1 gap-4 sm:grid-cols-2',
    optionGrid: 'mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3',
    programSourceGrid: 'mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3',
    optionButtonBase:
      'inline-flex cursor-pointer active:scale-[0.98] items-center justify-center rounded-xl border px-4 py-3.5 text-sm font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-primary/100 focus:ring-offset-2',
    optionButtonSelected: 'border-primary bg-primary text-white',
    optionButtonUnselected: 'border-slate-200 bg-white text-slate-700 hover:bg-slate-50',
    seeAllButton:
      'mt-3 inline-flex items-center justify-center text-sm font-semibold text-primary underline underline-offset-4 hover:text-primary',
    modalOverlay: 'fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4',
    modalCard:
      'w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl ring-1 ring-slate-900/10',
    modalHeader: 'flex items-center justify-between border-b border-slate-200 px-5 py-4',
    modalTitle: 'text-sm font-extrabold uppercase tracking-wide text-slate-800',
    modalCloseButton:
      'inline-flex items-center justify-center rounded-md bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-200',
    modalBody: 'px-5 py-5',
    copyrightText: 'absolute bottom-6 left-6 text-xs text-slate-400',
    buttonGroup: 'pt-2 space-y-3',
    imagePanel: 'relative hidden h-screen overflow-hidden bg-slate-50 lg:block lg:rounded-l-3xl',
    image: 'object-cover',
  },
};
