export const authTheme = {
  login: {
    inputWrapper: 'relative flex items-center',
    inputIcon: 'absolute left-4 h-5 w-5 text-slate-400',
    inputEyeBtn: 'absolute right-4 h-5 w-5 text-slate-400 hover:text-slate-600 transition-colors cursor-pointer',
    input:
      'w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-12 pr-3 text-sm text-slate-800 outline-none placeholder:text-slate-400 focus:border-[var(--brand-primary)] focus:ring-2 focus:ring-[var(--brand-primary)]/20 transition-all',
    inputPassword: 'pr-12',
    checkbox: 'h-4 w-4 rounded border-white/30 bg-white/20 text-primary focus:ring-primary/40',
    primaryButton:
      'inline-flex w-full cursor-pointer items-center justify-center rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white transition-all hover:bg-primary/90 active:scale-[0.98]',
    forgotPasswordLink: 'font-semibold cursor-pointer text-primary hover:text-primary/80 transition-colors',
    switchModeLink: 'font-semibold cursor-pointer text-primary hover:text-primary/80 transition-colors',
    slideIndicatorWrapper:
      'inline-flex items-center gap-1.5 bg-white/20 px-2 py-1.5 rounded-full',
    slideDotActive: 'h-1.5 w-5 rounded-full bg-yellow-400',
    slideDotInactive: 'h-1.5 w-1.5 rounded-full bg-white/70',
    heroEyebrow: 'text-xs font-semibold uppercase tracking-[0.24em] text-white/80',
    heroTitle: 'text-[28px] font-bold leading-tight text-white',
    heroDescription: 'text-sm text-white/80',
    pageBackground: 'bg-slate-50',
    imagePanelBackground: 'bg-slate-50',
    heroOverlay: 'absolute inset-0 bg-gradient-to-t from-[var(--brand-primary)] via-[var(--brand-primary)]/90 to-transparent',
    heroTextContainer: 'absolute inset-x-0 bottom-0 px-8 pb-20 pt-32 text-white',
    heroLogo: 'h-8 w-auto brightness-0 invert',
    heroLogoWrapper: 'space-y-3',
    formPanelOuter: 'flex items-center justify-center w-full h-full px-6 py-12 lg:px-16 lg:py-16',
    formPanelInner: 'w-full max-w-[480px]',
    formHeading: 'text-xl font-bold tracking-tight text-slate-900',
    formSubheading: 'mt-1.5 text-sm text-slate-500 mb-2',
    card: 'space-y-10 rounded-2xl border border-slate-100 bg-white p-10 sm:p-12 shadow-sm',
    fieldLabel: 'block text-xs font-semibold uppercase tracking-wide text-slate-600 mb-2',
    helperText: 'text-sm text-slate-600 text-center mt-2',
    checkboxRow: 'flex items-center justify-between text-sm text-slate-600',
    dividerRow:
      'flex items-center justify-center gap-3 text-[11px] font-medium uppercase tracking-[0.15em] text-slate-400',
    dividerLine: 'h-px w-20 bg-slate-200',
    socialSection: 'rounded-2xl border border-slate-200 bg-white p-4 shadow-sm',
    socialGrid: 'grid grid-cols-1 gap-3 sm:grid-cols-2',
    googleButton:
      'inline-flex w-full cursor-pointer items-center justify-center gap-3 rounded-xl border border-slate-200 bg-white px-5 py-4 hover:shadow-sm active:scale-[0.98] text-base font-medium text-slate-600 transition-all hover:bg-slate-50',
    googleButtonIcon: 'h-5 w-5',
    facebookButton:
      'inline-flex w-full cursor-pointer items-center justify-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-2.5 hover:shadow-sm active:scale-[0.98] text-[14px] font-bold text-slate-700 transition-all hover:bg-slate-50',
    facebookButtonIcon: 'h-5 w-5',
    secondaryButton:
      'inline-flex w-full cursor-pointer items-center justify-center rounded-xl border-2 border-[var(--brand-primary)] bg-transparent px-4 py-2.5 hover:shadow-sm active:scale-[0.98] text-[13px] font-bold text-primary uppercase tracking-[0.1em] transition-all hover:bg-primary/5',
    termsLabel: 'mt-1 inline-flex items-center gap-2 text-xs text-slate-600',
    termsLink: 'underline cursor-pointer',
  },
  onboarding: {
    layoutGrid: 'grid h-screen w-full grid-cols-1 overflow-hidden lg:grid-cols-[1fr_minmax(0,45%)]',
    leftCol: 'relative bg-white flex flex-col h-screen lg:rounded-r-3xl',
    leftCenter: 'flex-1 overflow-y-auto flex flex-col items-center justify-center px-6 py-10 sm:px-10 lg:px-16 lg:py-12 w-full',
    logoWrapper: 'mb-6',
    logoImage: 'h-14 w-auto sm:h-16',
    progressGrid: 'flex items-center gap-3 w-full',
    progressButtonBase: 'group flex-1',
    progressButtonLocked: 'cursor-not-allowed opacity-60',
    progressBarBase: 'h-1.5 w-full rounded-full transition-colors',
    progressBarActive: 'bg-primary',
    progressBarInactive: 'bg-slate-200',
    stepLine: 'mt-5 text-sm text-slate-500',
    stepLineEmphasis: 'font-semibold text-primary',
    questionTitle: 'mt-3 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl',
    questionDescription: 'mt-2 text-sm text-slate-500',
    form: 'mt-6 space-y-4 w-full',
    fieldError: 'mt-1 text-xs text-primary',
    locationGrid: 'grid grid-cols-1 gap-4 sm:grid-cols-2',
    optionGrid: 'mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3',
    programSourceGrid: 'mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3',
    optionButtonBase:
      'inline-flex cursor-pointer active:scale-[0.98] items-center justify-center rounded-xl border px-3 py-2.5 text-sm font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-primary/100 focus:ring-offset-2',
    optionButtonSelected: 'border-primary bg-primary text-white',
    optionButtonUnselected: 'border-slate-200 bg-white text-slate-700 hover:bg-slate-50',
    seeAllButton:
      'mt-3 inline-flex items-center justify-center text-sm font-semibold text-primary underline underline-offset-4 hover:text-primary',
    modalOverlay: 'fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4',
    modalCard:
      'w-full max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl ring-1 ring-slate-900/10',
    modalHeader: 'flex items-center justify-between border-b border-slate-200 px-5 py-4',
    modalTitle: 'text-sm font-extrabold uppercase tracking-wide text-slate-800',
    modalCloseButton:
      'inline-flex items-center justify-center rounded-md bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-200',
    modalBody: 'px-5 py-5',
    copyrightText: 'absolute bottom-6 left-6 text-xs text-slate-400',
    buttonGroup: 'pt-4 flex gap-3 w-full',
    imagePanel: 'relative hidden h-screen overflow-hidden lg:block',
    image: 'object-cover',
  },
};
// trigger tailwind cache
